export interface TodaySale {
  id: string
  name: string
  brand: string
  image: string
  originalPrice?: string
  currentPrice: string
  discountRate?: string
  averageRating: string
  ratingCount: string
  adTag: boolean
  tag?: string
}

export const todaySales: TodaySale[] = [
  {
    id: 'prod-001',
    brand: '차조',
    name: 'Deserunt 제품',
    image: 'https://picsum.photos/seed/prod1/300/300',
    originalPrice: '51416',
    currentPrice: '33492',
    discountRate: '35%',
    adTag: true,
    averageRating: '2.83',
    ratingCount: '571',
    tag: '식품',
  },
  {
    id: 'prod-002',
    brand: '김조',
    name: 'Temporibus 제품',
    image: 'https://picsum.photos/seed/prod2/300/300',
    originalPrice: '11214',
    currentPrice: '8399',
    discountRate: '25%',
    adTag: true,
    averageRating: '2.67',
    ratingCount: '527',
    tag: '가전',
  },
  {
    id: 'prod-003',
    brand: '김김',
    name: 'Natus 제품',
    image: 'https://picsum.photos/seed/prod3/300/300',
    originalPrice: '12513',
    currentPrice: '10385',
    discountRate: '17%',
    adTag: true,
    averageRating: '2.64',
    ratingCount: '528',
    tag: '디지털',
  },
  {
    id: 'prod-004',
    brand: '이이조',
    name: 'Nisi 제품',
    image: 'https://picsum.photos/seed/prod4/300/300',
    originalPrice: '45626',
    currentPrice: '40921',
    discountRate: '10%',
    adTag: true,
    averageRating: '3.57',
    ratingCount: '495',
    tag: '도서',
  },
  {
    id: 'prod-005',
    brand: '성최배',
    name: 'Ab 제품',
    image: 'https://picsum.photos/seed/prod5/300/300',
    originalPrice: '19484',
    currentPrice: '12126',
    discountRate: '38%',
    adTag: false,
    averageRating: '3.61',
    ratingCount: '536',
    tag: '패션',
  },
  {
    id: 'prod-006',
    brand: '이홍',
    name: 'Porro 제품',
    image: 'https://picsum.photos/seed/prod6/300/300',
    originalPrice: '55993',
    currentPrice: '44831',
    discountRate: '20%',
    adTag: false,
    averageRating: '3.2',
    ratingCount: '411',
    tag: '뷰티',
  },
  {
    id: 'prod-007',
    brand: '(주) 안권류',
    name: 'Sint 제품',
    image: 'https://picsum.photos/seed/prod7/300/300',
    originalPrice: '68761',
    currentPrice: '55466',
    discountRate: '19%',
    adTag: false,
    averageRating: '3.42',
    ratingCount: '953',
    tag: '반려',
  },
  {
    id: 'prod-008',
    brand: '주식회사 오',
    name: 'Veritatis 제품',
    image: 'https://picsum.photos/seed/prod8/300/300',
    originalPrice: '93178',
    currentPrice: '66514',
    discountRate: '29%',
    adTag: true,
    averageRating: '4.73',
    ratingCount: '61',
    tag: '패션',
  },
  {
    id: 'prod-009',
    brand: '(주) 김',
    name: 'Debitis 제품',
    image: 'https://picsum.photos/seed/prod9/300/300',
    originalPrice: '19787',
    currentPrice: '15711',
    discountRate: '21%',
    adTag: false,
    averageRating: '2.51',
    ratingCount: '172',
    tag: '반려',
  },
  {
    id: 'prod-010',
    brand: '김김',
    name: 'Iste 제품',
    image: 'https://picsum.photos/seed/prod10/300/300',
    originalPrice: '62404',
    currentPrice: '39613',
    discountRate: '37%',
    adTag: true,
    averageRating: '4.6',
    ratingCount: '786',
    tag: '뷰티',
  },
  {
    id: 'prod-011',
    brand: '(주) 윤',
    name: 'Blanditiis 제품',
    image: 'https://picsum.photos/seed/prod11/300/300',
    originalPrice: '31829',
    currentPrice: '29594',
    discountRate: '7%',
    adTag: true,
    averageRating: '4.82',
    ratingCount: '131',
    tag: '스포츠',
  },
  {
    id: 'prod-012',
    brand: '박김한',
    name: 'Consequuntur 제품',
    image: 'https://picsum.photos/seed/prod12/300/300',
    originalPrice: '50942',
    currentPrice: '38167',
    discountRate: '25%',
    adTag: true,
    averageRating: '3.3',
    ratingCount: '485',
    tag: '식품',
  },
  {
    id: 'prod-013',
    brand: '주식회사 한',
    name: 'Necessitatibus 제품',
    image: 'https://picsum.photos/seed/prod13/300/300',
    originalPrice: '57240',
    currentPrice: '43662',
    discountRate: '24%',
    adTag: false,
    averageRating: '3.61',
    ratingCount: '293',
    tag: '디지털',
  },
  {
    id: 'prod-014',
    brand: '박권고',
    name: 'Reiciendis 제품',
    image: 'https://picsum.photos/seed/prod14/300/300',
    originalPrice: '81455',
    currentPrice: '62213',
    discountRate: '24%',
    adTag: false,
    averageRating: '3.54',
    ratingCount: '100',
    tag: '가전',
  },
  {
    id: 'prod-015',
    brand: '심오김',
    name: 'Magnam 제품',
    image: 'https://picsum.photos/seed/prod15/300/300',
    originalPrice: '74149',
    currentPrice: '66128',
    discountRate: '11%',
    adTag: true,
    averageRating: '3.6',
    ratingCount: '385',
    tag: '뷰티',
  },
  {
    id: 'prod-016',
    brand: '이이',
    name: 'Voluptate 제품',
    image: 'https://picsum.photos/seed/prod16/300/300',
    originalPrice: '59051',
    currentPrice: '48707',
    discountRate: '18%',
    adTag: true,
    averageRating: '3.38',
    ratingCount: '85',
    tag: '도서',
  },
  {
    id: 'prod-017',
    brand: '최김이',
    name: 'Minus 제품',
    image: 'https://picsum.photos/seed/prod17/300/300',
    originalPrice: '16514',
    currentPrice: '12190',
    discountRate: '26%',
    adTag: false,
    averageRating: '4.15',
    ratingCount: '516',
    tag: '디지털',
  },
  {
    id: 'prod-018',
    brand: '송박',
    name: 'Eaque 제품',
    image: 'https://picsum.photos/seed/prod18/300/300',
    originalPrice: '55800',
    currentPrice: '41140',
    discountRate: '26%',
    adTag: true,
    averageRating: '3.71',
    ratingCount: '212',
    tag: '식품',
  },
  {
    id: 'prod-019',
    brand: '유한회사 김',
    name: 'Repellendus 제품',
    image: 'https://picsum.photos/seed/prod19/300/300',
    originalPrice: '57259',
    currentPrice: '39963',
    discountRate: '30%',
    adTag: true,
    averageRating: '4.79',
    ratingCount: '937',
    tag: '디지털',
  },
  {
    id: 'prod-020',
    brand: '(주) 이최장',
    name: 'Iure 제품',
    image: 'https://picsum.photos/seed/prod20/300/300',
    originalPrice: '13859',
    currentPrice: '10688',
    discountRate: '23%',
    adTag: false,
    averageRating: '4.16',
    ratingCount: '590',
    tag: '반려',
  },
  {
    id: 'prod-021',
    brand: '주식회사 최',
    name: 'Reiciendis 제품',
    image: 'https://picsum.photos/seed/prod21/300/300',
    originalPrice: '92631',
    currentPrice: '90286',
    discountRate: '3%',
    adTag: false,
    averageRating: '4.19',
    ratingCount: '576',
    tag: '디지털',
  },
  {
    id: 'prod-022',
    brand: '(주) 이',
    name: 'Porro 제품',
    image: 'https://picsum.photos/seed/prod22/300/300',
    originalPrice: '61956',
    currentPrice: '58290',
    discountRate: '6%',
    adTag: true,
    averageRating: '2.84',
    ratingCount: '688',
    tag: '취미',
  },
  {
    id: 'prod-023',
    brand: '(유) 김한진',
    name: 'Perferendis 제품',
    image: 'https://picsum.photos/seed/prod23/300/300',
    originalPrice: '10898',
    currentPrice: '6937',
    discountRate: '36%',
    adTag: true,
    averageRating: '2.73',
    ratingCount: '863',
    tag: '반려',
  },
  {
    id: 'prod-024',
    brand: '유한회사 이',
    name: 'Amet 제품',
    image: 'https://picsum.photos/seed/prod24/300/300',
    originalPrice: '61941',
    currentPrice: '50784',
    discountRate: '18%',
    adTag: true,
    averageRating: '4.46',
    ratingCount: '797',
    tag: '취미',
  },
  {
    id: 'prod-025',
    brand: '이김',
    name: 'Perspiciatis 제품',
    image: 'https://picsum.photos/seed/prod25/300/300',
    originalPrice: '51650',
    currentPrice: '49089',
    discountRate: '5%',
    adTag: true,
    averageRating: '3.8',
    ratingCount: '634',
    tag: '스포츠',
  },
  {
    id: 'prod-026',
    brand: '(유) 김하최',
    name: 'Ex 제품',
    image: 'https://picsum.photos/seed/prod26/300/300',
    originalPrice: '68628',
    currentPrice: '63114',
    discountRate: '8%',
    adTag: true,
    averageRating: '3.95',
    ratingCount: '238',
    tag: '반려',
  },
  {
    id: 'prod-027',
    brand: '정이강',
    name: 'Adipisci 제품',
    image: 'https://picsum.photos/seed/prod27/300/300',
    originalPrice: '90955',
    currentPrice: '62292',
    discountRate: '32%',
    adTag: false,
    averageRating: '3.33',
    ratingCount: '959',
    tag: '취미',
  },
  {
    id: 'prod-028',
    brand: '나이윤',
    name: 'Possimus 제품',
    image: 'https://picsum.photos/seed/prod28/300/300',
    originalPrice: '76751',
    currentPrice: '55292',
    discountRate: '28%',
    adTag: false,
    averageRating: '3.55',
    ratingCount: '985',
    tag: '도서',
  },
  {
    id: 'prod-029',
    brand: '한박곽',
    name: 'Sed 제품',
    image: 'https://picsum.photos/seed/prod29/300/300',
    originalPrice: '91820',
    currentPrice: '67238',
    discountRate: '27%',
    adTag: false,
    averageRating: '2.79',
    ratingCount: '83',
    tag: '반려',
  },
  {
    id: 'prod-030',
    brand: '김안박',
    name: 'Sunt 제품',
    image: 'https://picsum.photos/seed/prod30/300/300',
    originalPrice: '36652',
    currentPrice: '26060',
    discountRate: '29%',
    adTag: true,
    averageRating: '3.09',
    ratingCount: '242',
    tag: '뷰티',
  },
  {
    id: 'prod-031',
    brand: '(주) 손홍김',
    name: 'Magni 제품',
    image: 'https://picsum.photos/seed/prod31/300/300',
    originalPrice: '71340',
    currentPrice: '63121',
    discountRate: '12%',
    adTag: true,
    averageRating: '3.13',
    ratingCount: '143',
    tag: '뷰티',
  },
  {
    id: 'prod-032',
    brand: '김전이',
    name: 'Vero 제품',
    image: 'https://picsum.photos/seed/prod32/300/300',
    originalPrice: '49530',
    currentPrice: '30850',
    discountRate: '38%',
    adTag: true,
    averageRating: '3.5',
    ratingCount: '203',
    tag: '취미',
  },
  {
    id: 'prod-033',
    brand: '양최',
    name: 'Suscipit 제품',
    image: 'https://picsum.photos/seed/prod33/300/300',
    originalPrice: '88987',
    currentPrice: '82132',
    discountRate: '8%',
    adTag: false,
    averageRating: '3.57',
    ratingCount: '983',
    tag: '반려',
  },
  {
    id: 'prod-034',
    brand: '(유) 안서이',
    name: 'Exercitationem 제품',
    image: 'https://picsum.photos/seed/prod34/300/300',
    originalPrice: '42793',
    currentPrice: '26952',
    discountRate: '37%',
    adTag: false,
    averageRating: '4.19',
    ratingCount: '235',
    tag: '취미',
  },
  {
    id: 'prod-035',
    brand: '(유) 박',
    name: 'Minus 제품',
    image: 'https://picsum.photos/seed/prod35/300/300',
    originalPrice: '77377',
    currentPrice: '75951',
    discountRate: '2%',
    adTag: false,
    averageRating: '2.65',
    ratingCount: '908',
    tag: '반려',
  },
  {
    id: 'prod-036',
    brand: '황김',
    name: 'Sed 제품',
    image: 'https://picsum.photos/seed/prod36/300/300',
    originalPrice: '68333',
    currentPrice: '48670',
    discountRate: '29%',
    adTag: false,
    averageRating: '4.91',
    ratingCount: '943',
    tag: '도서',
  },
  {
    id: 'prod-037',
    brand: '김한',
    name: 'Dolores 제품',
    image: 'https://picsum.photos/seed/prod37/300/300',
    originalPrice: '54447',
    currentPrice: '46105',
    discountRate: '15%',
    adTag: true,
    averageRating: '3.54',
    ratingCount: '776',
    tag: '생활',
  },
  {
    id: 'prod-038',
    brand: '서배',
    name: 'Ipsum 제품',
    image: 'https://picsum.photos/seed/prod38/300/300',
    originalPrice: '27625',
    currentPrice: '15375',
    discountRate: '44%',
    adTag: false,
    averageRating: '3.24',
    ratingCount: '648',
    tag: '생활',
  },
  {
    id: 'prod-039',
    brand: '안이',
    name: 'Molestiae 제품',
    image: 'https://picsum.photos/seed/prod39/300/300',
    originalPrice: '14338',
    currentPrice: '9361',
    discountRate: '35%',
    adTag: false,
    averageRating: '3.85',
    ratingCount: '532',
    tag: '스포츠',
  },
  {
    id: 'prod-040',
    brand: '김김손',
    name: 'Id 제품',
    image: 'https://picsum.photos/seed/prod40/300/300',
    originalPrice: '30722',
    currentPrice: '18311',
    discountRate: '40%',
    adTag: true,
    averageRating: '4.1',
    ratingCount: '642',
    tag: '도서',
  },
  {
    id: 'prod-041',
    brand: '이권',
    name: 'Assumenda 제품',
    image: 'https://picsum.photos/seed/prod41/300/300',
    originalPrice: '66542',
    currentPrice: '64260',
    discountRate: '3%',
    adTag: false,
    averageRating: '3.31',
    ratingCount: '813',
    tag: '패션',
  },
  {
    id: 'prod-042',
    brand: '이엄이',
    name: 'Reprehenderit 제품',
    image: 'https://picsum.photos/seed/prod42/300/300',
    originalPrice: '69326',
    currentPrice: '51267',
    discountRate: '26%',
    adTag: false,
    averageRating: '3.4',
    ratingCount: '58',
    tag: '식품',
  },
  {
    id: 'prod-043',
    brand: '이윤양',
    name: 'Autem 제품',
    image: 'https://picsum.photos/seed/prod43/300/300',
    originalPrice: '92290',
    currentPrice: '54999',
    discountRate: '40%',
    adTag: true,
    averageRating: '4.07',
    ratingCount: '12',
    tag: '식품',
  },
  {
    id: 'prod-044',
    brand: '장곽',
    name: 'Aliquid 제품',
    image: 'https://picsum.photos/seed/prod44/300/300',
    originalPrice: '85793',
    currentPrice: '52614',
    discountRate: '39%',
    adTag: false,
    averageRating: '2.93',
    ratingCount: '229',
    tag: '도서',
  },
  {
    id: 'prod-045',
    brand: '주식회사 박손김',
    name: 'Quam 제품',
    image: 'https://picsum.photos/seed/prod45/300/300',
    originalPrice: '23512',
    currentPrice: '18127',
    discountRate: '23%',
    adTag: true,
    averageRating: '4.8',
    ratingCount: '836',
    tag: '스포츠',
  },
  {
    id: 'prod-046',
    brand: '김서',
    name: 'Numquam 제품',
    image: 'https://picsum.photos/seed/prod46/300/300',
    originalPrice: '95440',
    currentPrice: '48637',
    discountRate: '49%',
    adTag: false,
    averageRating: '4.38',
    ratingCount: '290',
    tag: '가전',
  },
  {
    id: 'prod-047',
    brand: '주식회사 김',
    name: 'Ipsa 제품',
    image: 'https://picsum.photos/seed/prod47/300/300',
    originalPrice: '68217',
    currentPrice: '58740',
    discountRate: '14%',
    adTag: true,
    averageRating: '2.85',
    ratingCount: '546',
    tag: '스포츠',
  },
  {
    id: 'prod-048',
    brand: '주식회사 최지김',
    name: 'Soluta 제품',
    image: 'https://picsum.photos/seed/prod48/300/300',
    originalPrice: '99608',
    currentPrice: '53179',
    discountRate: '47%',
    adTag: true,
    averageRating: '4.52',
    ratingCount: '858',
    tag: '가전',
  },
  {
    id: 'prod-049',
    brand: '(주) 김이한',
    name: 'Voluptatum 제품',
    image: 'https://picsum.photos/seed/prod49/300/300',
    originalPrice: '75322',
    currentPrice: '40907',
    discountRate: '46%',
    adTag: false,
    averageRating: '4.25',
    ratingCount: '776',
    tag: '가전',
  },
  {
    id: 'prod-050',
    brand: '(유) 차',
    name: 'Vel 제품',
    image: 'https://picsum.photos/seed/prod50/300/300',
    originalPrice: '56764',
    currentPrice: '39880',
    discountRate: '30%',
    adTag: true,
    averageRating: '4.46',
    ratingCount: '780',
    tag: '디지털',
  },
]
