export interface TodayDeal {
  id: string
  name: string
  brand: string
  image: string
  originalPrice?: string
  currentPrice: string
  discountRate?: string
  averageRating: string
  ratingCount: string
  adTag: boolean
  tag?: string
}

export const todaydeals: TodayDeal[] = [
  {
    id: 'prod-001',
    brand: '차조',
    name: 'Deserunt 제품',
    image: 'https://picsum.photos/seed/prod1/300/300',
    originalPrice: '51416',
    currentPrice: '33492',
    discountRate: '35%',
    adTag: true,
    averageRating: '2.83',
    ratingCount: '571',
    tag: '식품',
  },
  {
    id: 'prod-002',
    brand: '김조',
    name: 'Temporibus 제품',
    image: 'https://picsum.photos/seed/prod2/300/300',
    originalPrice: '11214',
    currentPrice: '8399',
    discountRate: '25%',
    adTag: true,
    averageRating: '2.67',
    ratingCount: '527',
    tag: '가전',
  },
  {
    id: 'prod-003',
    brand: '김김',
    name: 'Natus 제품',
    image: 'https://picsum.photos/seed/prod3/300/300',
    originalPrice: '12513',
    currentPrice: '10385',
    discountRate: '17%',
    adTag: true,
    averageRating: '2.64',
    ratingCount: '528',
    tag: '디지털',
  },
  {
    id: 'prod-004',
    brand: '이이조',
    name: 'Nisi 제품',
    image: 'https://picsum.photos/seed/prod4/300/300',
    originalPrice: '45626',
    currentPrice: '40921',
    discountRate: '10%',
    adTag: true,
    averageRating: '3.57',
    ratingCount: '495',
    tag: '도서',
  },
  {
    id: 'prod-005',
    brand: '성최배',
    name: 'Ab 제품',
    image: 'https://picsum.photos/seed/prod5/300/300',
    originalPrice: '19484',
    currentPrice: '12126',
    discountRate: '38%',
    adTag: false,
    averageRating: '3.61',
    ratingCount: '536',
    tag: '패션',
  },
  {
    id: 'prod-006',
    brand: '이홍',
    name: 'Porro 제품',
    image: 'https://picsum.photos/seed/prod6/300/300',
    originalPrice: '55993',
    currentPrice: '44831',
    discountRate: '20%',
    adTag: false,
    averageRating: '3.2',
    ratingCount: '411',
    tag: '뷰티',
  },
  {
    id: 'prod-007',
    brand: '(주) 안권류',
    name: 'Sint 제품',
    image: 'https://picsum.photos/seed/prod7/300/300',
    originalPrice: '68761',
    currentPrice: '55466',
    discountRate: '19%',
    adTag: false,
    averageRating: '3.42',
    ratingCount: '953',
    tag: '반려',
  },
  {
    id: 'prod-008',
    brand: '주식회사 오',
    name: 'Veritatis 제품',
    image: 'https://picsum.photos/seed/prod8/300/300',
    originalPrice: '93178',
    currentPrice: '66514',
    discountRate: '29%',
    adTag: true,
    averageRating: '4.73',
    ratingCount: '61',
    tag: '패션',
  },
  {
    id: 'prod-009',
    brand: '(주) 김',
    name: 'Debitis 제품',
    image: 'https://picsum.photos/seed/prod9/300/300',
    originalPrice: '19787',
    currentPrice: '15711',
    discountRate: '21%',
    adTag: false,
    averageRating: '2.51',
    ratingCount: '172',
    tag: '반려',
  },
  {
    id: 'prod-010',
    brand: '김김',
    name: 'Iste 제품',
    image: 'https://picsum.photos/seed/prod10/300/300',
    originalPrice: '62404',
    currentPrice: '39613',
    discountRate: '37%',
    adTag: true,
    averageRating: '4.6',
    ratingCount: '786',
    tag: '뷰티',
  },
  {
    id: 'prod-011',
    brand: '(주) 윤',
    name: 'Blanditiis 제품',
    image: 'https://picsum.photos/seed/prod11/300/300',
    originalPrice: '31829',
    currentPrice: '29594',
    discountRate: '7%',
    adTag: true,
    averageRating: '4.82',
    ratingCount: '131',
    tag: '스포츠',
  },
  {
    id: 'prod-012',
    brand: '박김한',
    name: 'Consequuntur 제품',
    image: 'https://picsum.photos/seed/prod12/300/300',
    originalPrice: '50942',
    currentPrice: '38167',
    discountRate: '25%',
    adTag: true,
    averageRating: '3.3',
    ratingCount: '485',
    tag: '식품',
  },
  {
    id: 'prod-013',
    brand: '주식회사 한',
    name: 'Necessitatibus 제품',
    image: 'https://picsum.photos/seed/prod13/300/300',
    originalPrice: '57240',
    currentPrice: '43662',
    discountRate: '24%',
    adTag: false,
    averageRating: '3.61',
    ratingCount: '293',
    tag: '디지털',
  },
  {
    id: 'prod-014',
    brand: '박권고',
    name: 'Reiciendis 제품',
    image: 'https://picsum.photos/seed/prod14/300/300',
    originalPrice: '81455',
    currentPrice: '62213',
    discountRate: '24%',
    adTag: false,
    averageRating: '3.54',
    ratingCount: '100',
    tag: '가전',
  },
  {
    id: 'prod-015',
    brand: '심오김',
    name: 'Magnam 제품',
    image: 'https://picsum.photos/seed/prod15/300/300',
    originalPrice: '74149',
    currentPrice: '66128',
    discountRate: '11%',
    adTag: true,
    averageRating: '3.6',
    ratingCount: '385',
    tag: '뷰티',
  },
  {
    id: 'prod-016',
    brand: '이이',
    name: 'Voluptate 제품',
    image: 'https://picsum.photos/seed/prod16/300/300',
    originalPrice: '59051',
    currentPrice: '48707',
    discountRate: '18%',
    adTag: true,
    averageRating: '3.38',
    ratingCount: '85',
    tag: '도서',
  },
  {
    id: 'prod-017',
    brand: '최김이',
    name: 'Minus 제품',
    image: 'https://picsum.photos/seed/prod17/300/300',
    originalPrice: '16514',
    currentPrice: '12190',
    discountRate: '26%',
    adTag: false,
    averageRating: '4.15',
    ratingCount: '516',
    tag: '디지털',
  },
  {
    id: 'prod-018',
    brand: '송박',
    name: 'Eaque 제품',
    image: 'https://picsum.photos/seed/prod18/300/300',
    originalPrice: '55800',
    currentPrice: '41140',
    discountRate: '26%',
    adTag: true,
    averageRating: '3.71',
    ratingCount: '212',
    tag: '식품',
  },
  {
    id: 'prod-019',
    brand: '유한회사 김',
    name: 'Repellendus 제품',
    image: 'https://picsum.photos/seed/prod19/300/300',
    originalPrice: '57259',
    currentPrice: '39963',
    discountRate: '30%',
    adTag: true,
    averageRating: '4.79',
    ratingCount: '937',
    tag: '디지털',
  },
  {
    id: 'prod-020',
    brand: '(주) 이최장',
    name: 'Iure 제품',
    image: 'https://picsum.photos/seed/prod20/300/300',
    originalPrice: '13859',
    currentPrice: '10688',
    discountRate: '23%',
    adTag: false,
    averageRating: '4.16',
    ratingCount: '590',
    tag: '반려',
  },
]
